export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERR = "REGISTER_ERR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERR = "LOGIN_ERR";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERR = "ADD_PRODUCT_ERR";

export const PRODUCT_SHOW_REQUEST = "PRODUCT_SHOW_REQUEST";
export const PRODUCT_SHOW_SUCCESS = "PRODUCT_SHOW_SUCCESS";
export const PRODUCT_SHOW_ERR = "PRODUCT_SHOW_ERR";

export const EDIT_PRO_SHOW_REQUEST = "EDIT_PRO_SHOW_REQUEST";
export const EDIT_PRO_SHOW_SUCCESS = "EDIT_PRO_SHOW_SUCCESS";
export const EDIT_PRO_SHOW_ERR = "EDIT_PRO_SHOW_ERR";

export const DELETE_PRO_REQUEST = "DELETE_PRO_REQUEST";
export const DELETE_PRO_SUCCESS = "DELETE_PRO_SUCCESS";
export const DELETE_PRO_ERR = "DELETE_PRO_ERR";

export const USER_SHOW_ALL_PRO_REQUEST = "USER_SHOW_ALL_PRO_REQUEST";
export const USER_SHOW_ALL_PRO_SUCCESS = "USER_SHOW_ALL_PRO_SUCCESS";
export const USER_SHOW_ALL_PRO_ERR = "USER_SHOW_ALL_PRO_ERR";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERR = "EDIT_POST_ERR";

export const EDIT_GET_DETAIL_REQUEST = "EDIT_GET_DETAIL_REQUEST";
export const EDIT_GET_DETAIL_SUCCESS = "EDIT_GET_DETAIL_SUCCESS";
export const EDIT_GET_DETAIL_ERR = "EDIT_GET_DETAIL_ERR";
